src/Entity/Episode.php
<?php

namespace App\Entity;

use App\Repository\EpisodeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EpisodeRepository::class)
 */
class Episode
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $season_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="text")
     */
    private $synopsis;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSeasonId(): ?int
    {
        return $this->season_id;
    }

    public function setSeasonId(int $season_id): self
    {
        $this->season_id = $season_id;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\Season", inversedBy="episodes")
     * @ORM\JoinColumn (nullable=false)
     */
    private $season;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    public function getSeason(): ?Season
    {
        return $this->season;
    }

    public function setSeason(?Season $season): self
    {
        $this->season = $season;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="episode", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }


    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEpisode($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEpisode() === $this) {
                $comment->setEpisode(null);
            }
        }

        return $this;
    }
}

src/Form/EpisodeType.php
<?php

namespace App\Form;

use App\Entity\Episode;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EpisodeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('season_id')
            ->add('number')
            ->add('synopsis')
            ->add('season', null, ['choice_label' => 'number'])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Episode::class,
        ]);
    }
}

src/Controller/EpisodeController.php
<?php

namespace App\Controller;

use App\Entity\Episode;
use App\Form\EpisodeType;
use App\Repository\EpisodeRepository;
use App\Service\Slugify;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/episode")
 */
class EpisodeController extends AbstractController
{
    /**
     * @Route("/", name="episode_index", methods={"GET"})
     */
    public function index(EpisodeRepository $episodeRepository): Response
    {
        $episode = new Episode();
        $season = $episode->getSeason();
        return $this->render('episode/index.html.twig', [
            'episodes' => $episodeRepository->findAll(), 'season' => $season]);
    }

    /**
     * @Route("/new", name="episode_new", methods={"GET","POST"})
     * @param Request $request
     * @param Slugify $slugify
     * @return Response
     */
    public function new(Request $request, Slugify $slugify, MailerInterface $mailer): Response
    {
        $episode = new Episode();
        $form = $this->createForm(EpisodeType::class, $episode);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $slug = $slugify->generate($episode->getTitle());
            $episode->setSlug($slug);
            $entityManager->persist($episode);
            $entityManager->flush();

            $this->addFlash('success', 'Le nouvel épisode de ' . $episode->getSeason()->getProgram()->getTitle() . ' a bien été crée');


            $email = (new Email())
                ->from($this->getParameter('mailer_from'))
                ->to('your_email@example.com')
                ->subject('Un nouvel épisode vient d\'être publié !')
                ->html($this->renderView('episode/newEpisodeEmail.html.twig', ['episode' => $episode]));


            $mailer->send($email);

            return $this->redirectToRoute('episode_index');
        }

        return $this->render('episode/new.html.twig', [
            'episode' => $episode,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="episode_show", methods={"GET"})
     */
    public function show(Episode $episode): Response
    {
        return $this->render('episode/show.html.twig', [
            'episode' => $episode,
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="episode_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Episode $episode, Slugify $slugify): Response
    {
        $form = $this->createForm(EpisodeType::class, $episode);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = $slugify->generate($episode->getTitle());
            $episode->setSlug($slug);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Le nouvel épisode de ' . $episode->getSeason()->getProgram()->getTitle() . ' a bien été modifié');


            return $this->redirectToRoute('episode_index');
        }

        return $this->render('episode/edit.html.twig', [
            'episode' => $episode,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="episode_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Episode $episode): Response
    {
        if ($this->isCsrfTokenValid('delete'.$episode->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($episode);
            $entityManager->flush();

            $this->addFlash('danger', 'Vous venez de supprimer un épide de ' . $episode->getSeason()->getProgram()->getTitle());

        }

        return $this->redirectToRoute('episode_index');
    }
}

templates/episode/_delete_form.html.twig
<form method="post" action="{{ path('episode_delete', {'id': episode.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ episode.id) }}">
    <button class="btn">Delete</button>
</form>

templates/episode/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Episode{% endblock %}

{% block body %}
    <h1>Edit Episode</h1>

    {{ include('episode/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('episode_index') }}">back to list</a>

    {{ include('episode/_delete_form.html.twig') }}
{% endblock %}

templates/episode/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Episode index{% endblock %}

{% block body %}
    <h1>Episode index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Season_id</th>
                <th>Number</th>
                <th>Synopsis</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for episode in episodes %}
            <tr>
                <td>{{ episode.id }}</td>
                <td>{{ episode.title }}</td>
                <td>{{ episode.seasonId }}</td>
                <td>{{ episode.number }}</td>
                <td>{{ episode.synopsis }}</td>
                <td>
                    <a href="{{ path('episode_show', {'slug': episode.slug}) }}">show</a>
                    <a href="{{ path('episode_edit', {'slug': episode.slug}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('episode_new') }}">Create new</a>
{% endblock %}

templates/episode/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Episode{% endblock %}

{% block body %}
    <h1>Create new Episode</h1>

    {{ include('episode/_form.html.twig') }}

    <a href="{{ path('episode_index') }}">back to list</a>
{% endblock %}

templates/episode/newEpisodeEmail.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>New épisode</title>
</head>
<body>
<h1>New episode {{ episode.title }} created</h1>
<p>Hello, the new episode {{ episode.title }} has been created on Wild Series</p>
<p>Summary : {{episode.synopsis }}
</body>
</html>

templates/episode/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Episode{% endblock %}

{% block body %}
    <h1>Episode</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ episode.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ episode.title }}</td>
            </tr>
            <tr>
                <th>Season_id</th>
                <td>{{ episode.seasonId }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ episode.number }}</td>
            </tr>
            <tr>
                <th>Synopsis</th>
                <td>{{ episode.synopsis }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('episode_index') }}">back to list</a>

    <a href="{{ path('episode_edit', {'id': episode.id}) }}">edit</a>

    {{ include('episode/_delete_form.html.twig') }}
{% endblock %}