src/Entity/Season.php
<?php

namespace App\Entity;

use App\Repository\SeasonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SeasonRepository::class)
 */
class Season
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $program_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="integer")
     */
    private $year;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProgramId(): ?int
    {
        return $this->program_id;
    }

    public function setProgramId(int $program_id): self
    {
        $this->program_id = $program_id;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\Program", inversedBy="seasons")
     * @ORM\JoinColumn (nullable=false)
     */
    private $program;

    public function getProgram(): ?Program
    {
        return $this->program;
    }

    public function setProgram(?Program $program): self
    {
        $this->program = $program;

        return $this;
    }


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Episode", mappedBy="season")
     */
    private $episodes;

    public function __construct()
    {
        $this->episodes = new ArrayCollection();
    }

    /**
     * @return Collection|Episode[]
     */
    public function getEpisodes(): Collection
    {
        return $this->episodes;
    }

    /**
     * @param Episode $episode
     * @return Season
     */
    public function addEpisode(Season $episode): self
    {
        if (!$this->episodes->contains($episode)){
            $this->episodes[] = $episode;
            $episode->setSeason($this);
        }
        return $this;

    }

    /**
     * @param Episode $episode
     * @return Season
     */
    public function removeEpisode(Season $episode): self
    {
        if ($this->episodes->contains($episode)){
            $this->episodes->removeElement($episode);
            if ($episode->getSeason() === $this) {
                $episode->setSeason(null);
            }
        }
        return $this;
    }
}

src/Form/SeasonType.php
<?php

namespace App\Form;

use App\Entity\Season;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SeasonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('program_id')
            ->add('number')
            ->add('year')
            ->add('description')
            ->add('program', null, ['choice_label' => 'title'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Season::class,
        ]);
    }
}

src/Controller/SeasonController.php
<?php

namespace App\Controller;

use App\Entity\Season;
use App\Form\SeasonType;
use App\Repository\SeasonRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/season")
 */
class SeasonController extends AbstractController
{
    /**
     * @Route("/", name="season_index", methods={"GET"})
     */
    public function index(SeasonRepository $seasonRepository): Response
    {
        return $this->render('season/index.html.twig', [
            'seasons' => $seasonRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="season_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $season = new Season();
        $form = $this->createForm(SeasonType::class, $season);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($season);
            $entityManager->flush();

            $this->addFlash('success', 'La nouvelle saison de ' . $season->getProgram()->getTitle() . ' a bien été créé');


            return $this->redirectToRoute('season_index');
        }

        return $this->render('season/new.html.twig', [
            'season' => $season,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="season_show", methods={"GET"})
     */
    public function show(Season $season): Response
    {
        return $this->render('season/show.html.twig', [
            'season' => $season,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="season_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Season $season): Response
    {
        $form = $this->createForm(SeasonType::class, $season);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'La nouvelle saison de ' . $season->getProgram()->getTitle() . ' a bien été modifié');

            return $this->redirectToRoute('season_index');
        }

        return $this->render('season/edit.html.twig', [
            'season' => $season,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="season_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Season $season): Response
    {
        if ($this->isCsrfTokenValid('delete'.$season->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($season);
            $entityManager->flush();

            $this->addFlash('danger', 'La saison' . $season->getNumber() . ' de ' . $season->getProgram()->getTitle() . 'a bien été supprimé');

        }

        return $this->redirectToRoute('season_index');
    }
}

templates/season/_delete_form.html.twig
<form method="post" action="{{ path('season_delete', {'id': season.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ season.id) }}">
    <button class="btn">Delete</button>
</form>

templates/season/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Season{% endblock %}

{% block body %}
    <h1>Edit Season</h1>

    {{ include('season/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('season_index') }}">back to list</a>

    {{ include('season/_delete_form.html.twig') }}
{% endblock %}

templates/season/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Season index{% endblock %}

{% block body %}
    <h1>Season index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Program_id</th>
                <th>Number</th>
                <th>Year</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for season in seasons %}
            <tr>
                <td>{{ season.id }}</td>
                <td>{{ season.programId }}</td>
                <td>{{ season.number }}</td>
                <td>{{ season.year }}</td>
                <td>{{ season.description }}</td>
                <td>
                    <a href="{{ path('season_show', {'id': season.id}) }}">show</a>
                    <a href="{{ path('season_edit', {'id': season.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('season_new') }}">Create new</a>
{% endblock %}

templates/season/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Season{% endblock %}

{% block body %}
    <h1>Create new Season</h1>

    {{ include('season/_form.html.twig') }}

    <a href="{{ path('season_index') }}">back to list</a>
{% endblock %}

templates/season/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Season{% endblock %}

{% block body %}
    <h1>Season</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ season.id }}</td>
            </tr>
            <tr>
                <th>Program_id</th>
                <td>{{ season.programId }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ season.number }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ season.year }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ season.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('season_index') }}">back to list</a>

    <a href="{{ path('season_edit', {'id': season.id}) }}">edit</a>

    {{ include('season/_delete_form.html.twig') }}
{% endblock %}